### ISSUE TITLE
Creating unique keys when generating all possible choices

### ISSUE THREAD

**Issue by gtng92** [PoonLab/treeswithintrees#20]
A partial example YAML file:
```yaml
Compartments:
  'I':
    type: host                         # CompartmentType 
    replicates: 100  
Lineages:
  'I':
    sampling.time: 0             
    location: I
    replicates: 6                      # implied to be per-host
```
There are 100 Compartments, each with 6 Lineages.

When generating all possible choices for inner-tree simulation, there is a problem when it comes to unique names. Currently, unique names are generated on the back end, taking the name of the Compartment or Lineage, and attaching '_#', where '#' increments according to the specified number of replicates. 

For example, Compartment `I_2` will have Lineages `I_1` to `I_6`. For each pair, I generate a unique name by:
```R
# 'Lineage1Name,Lineage2Name' <- 'CompartmentName'
self$choices[[paste(pair[1], pair[2], sep=',')]] <- names(self$locations)[[hostNum]]
```
But all possible pairs within Compartment `I_2` will have the same "unique" names as the Lineages within Compartment `I_3`, Compartment `I_4`, and so on.
