### ISSUE TITLE
Creating specific pointers for Lineages' initial `location` and Compartments' initial `source`

### ISSUE THREAD

**Issue by gtng92** [PoonLab/treeswithintrees#9]
```yaml
Compartments:
  'A':                              # label is linked to Newick tree tip label
    type: host                      # reference to CompartmentType object
    source: undefined               # A is the root
    inf.time: undefined
    sampling.time: 0.0
    pop.size: 1                     # would be used for replication of generic object (80 hosts of type 1)
  'B':
    type: host
    source: A
    inf.time: 3.0                   # note this is reverse time
    sampling.time: 0.0
    pop.size: 1
  'C': 
    type: host
    source: B
    inf.time: 1.0
    sampling.time: 0.0
    pop.size: 1
Lineages:
  '1': 
    type: virus
    sampling.time: (0.0, 2.0, 3.0)  # could either be a single sampling time, or a vector of multiple, where we will then create distinct Lineages
    location: A                     # at sampling, will change as we go back in time
    pop.size: 3
  '2': 
    type: virus
    sampling.time: 0.0
    location: B
    pop.size: 1
  '3': 
    type: virus
    sampling.time: 0.0
    location: C
    pop.size: 1
```
If the above file was provided as user-input, the following would be generated:
  * 1 Compartment labeled as `A_1`
  * 1 Compartment labeled as `B_1`
  * 1 Compartment labeled as `C_1`
  * 3 Lineages located in Compartment A labeled as `1_1`, `1_2`, and `1_3`
  * 1 Lineage located in Compartment B labeled as `2_1`
  * 1 Lineage located in Compartment C labeled as `3_1`

Currently, the user does not need to explicitly specify the initial `location` of Lineage objects, or the initial `source` of Compartment objects. 

In the current implementation (276b322), it is assumed the location or source is the first object in a given Compartment, if the label is found. For example, Lineages `1_1`, `1_2`, and `1_3` will have their `location` attributes point to object `A_1`. 

This presents a problem when the `pop.size` of Compartment object is greater than 1 (ie. `example3.yaml`)
```yaml
Compartments:
  'blood':
    type: blood                                  # reference to CompartmentType object
    pop.size: 1
  'cell':
    type: cell
    pop.size: 100                                # sampled, not total!
Lineages:
  'blood':
    location: blood
    pop.size: 100
    sampling.time: undefined
  'cell':
    location: cell
    pop.size: 1                                   # if location has pop.size, then this is applied to each
    sampling.time: undefined
```
